version: '3.8'
services:
  postgresql:
    image: postgres:alpine
    container_name: "postgres-db"
    environment:
      - POSTGRES_DB=webflux
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      timeout: 15s
      retries: 10
#volumes:
#  - postgres_data:/data/db
#  pgadmin:
#    container_name: pgadmin4
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: password
#    ports:
#      - "5050:80"
#    volumes:
#      - pgadmin_data:/data/pgadmin

#volumes:
#  postgres_data:
#  pgadmin_data:
