version: '3.8'
services:
  postgresql:
    image: postgres:alpine
    container_name: "postgresql"
    environment:
      - POSTGRES_DB=spring
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "8082:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      timeout: 15s
      retries: 10

  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - postgresql
