spring:
  r2dbc:
    url: r2dbc:postgresql://172.17.0.1:5432/spring
    username: postgres
    password: secret

logging:
  level:
    root: info
    sql: trace
    web: debug
    com.turbo: debug
    r2dbc: debug
  group:
    r2dbc: org.springframework.r2dbc,org.springframework.data.r2dbc
